### ISSUE TITLE
Unable to Invoke Contract on Ethereum Sepolia Testnet from Xrpl Ledger Testnet

### ISSUE THREAD

**Issue by RaumTora** [axelarnetwork/support#183]
Hey can anyone help me with this , somehow my destination contract's _executeWithInterchainToken is not being called ,it is showing approved for a lot of time but never being progressed to Executed State

Attaching screenshot for reference , my contract's logic is working fine as my team is already using it for CCIP and CCTP for testing.

Any help would be appreciated ,transaction is from XRP Ledger Testnet to Ethereum Sepolia

Transaction ID - [https://testnet.axelarscan.io/gmp/BE23ADCE487C70367ABD81E3690F2495C2300E8B1B046F513759B2DCA3BEFBD3](https://testnet.axelarscan.io/gmp/BE23ADCE487C70367ABD81E3690F2495C2300E8B1B046F513759B2DCA3BEFBD3)

<img width="1309" height="753" alt="Image" src="https://github.com/user-attachments/assets/5c53defa-9ceb-4c1a-bcbb-9df8ebffc165" />

**Comment by benjamin852** [comment]
Hey @RaumTora there is a `revert` coming from the contract we have pushed a fix to axelarscan so it renders the appropriate error message rather than just hanging. The reason the tx is not going through though is due to an error on the contract, specifically the following: `code 43: EstimationReverted: execution reverted: TransferHelper::safeTransferETH: ETH transfer failed`

**Comment by RaumTora** [comment]
@benjamin852 can you share the transaction hash as well for the failed transaction so that i can debug for the same , because in my contract there is no code 43 defined

**Comment by benjamin852** [comment]
Hey, sorry for the delay here. The transaction was never executed on-chain; the revert occurred during Axelar’s simulation (gas estimation) phase.

**Comment by RaumTora** [comment]
@benjamin852 can you please share the contract that is simulating the transaction or that initiates the transaction so i can see what approvals are needed so i dont get the safeTransfers error

**Comment by benjamin852** [comment]
Hey @RaumTora it should be happening right [here](https://github.com/axelarnetwork/interchain-token-service/blob/main/contracts/TokenHandler.sol#L163)

**Comment by RaumTora** [comment]
Hi @benjamin852  Can you please share me the contract address on Ethereum Sepolia so i can pinpoint the error by simulation or somewhere on your side so i can see where it fails and that can be debugged because  **TransferHelper::safeTransferETH: ETH transfer failed** happens when 

1.The recipient contract doesn’t have a payable fallback function. -> receive() external payable {} present in my contract

2.The call runs out of gas. -> No idea since i don't know what are the calls being made.

3.The address is invalid. -> My Contract is deployed on Sepolia

Can you please help me so i can pinpoint the issue and close it.

**Comment by benjamin852** [comment]
The ITS contract can be found [here](https://sepolia.etherscan.io/address/0xB5FB4BE02232B1bBA4dC8f81dc24C26980dE9e3C#readProxyContract), having said that your own [token manager](https://docs.axelar.dev/dev/send-tokens/interchain-tokens/token-manager/) the contract that is making the call is deployed [here](https://sepolia.etherscan.io/address/0xdb0a778c57Bd31E401D52ba6cf936D06E1324aE8) on sepolia. Can you confirm if you granted your manager the minter role on the token? Thanks

**Comment by RaumTora** [comment]
@benjamin852 i am using the token deployed via ITS i.e it comes in the native category right , i am using XRP from XRP Ledger to Ethereum Sepolia , since it's a interchain token native transfer i don't need the Minter Role right , it is already with the ITS side as well as i can show other transaction as well where i can transfer XRP from XRP Ledger to Ethereum Sepolia without making extra call arguments and it works . Here is that transaction - [https://testnet.axelarscan.io/gmp/0xde74e3a5c07cec27a42aaa6bb009c16b115f5139ea412842a5dc35975cca8279](https://testnet.axelarscan.io/gmp/0xde74e3a5c07cec27a42aaa6bb009c16b115f5139ea412842a5dc35975cca8279) So i can only assume it is something else that is giving the error beside the minter role

**Comment by benjamin852** [comment]
Ah I see yes, okay it is not a whitelisting issue I checked and see the relevant manager is whitelisted. And other cross-chain txs for this ITS asset are going through fine, so it's not an issue with the given token's integration to ITS. You mentioned in your original post you're atttempting to call `_executeWithInterchainToken`. What is the custom logic you're trying to trigger in that fn? I am assuming that's where the simulate failure is occuring.

**Comment by RaumTora** [comment]
@benjamin852 here is my custom logic that i am trying to process 

`IERC20(token).approve(address(dexRouter), amount);
    
      address[] memory path = new address[](2);
        path[0] = address(token);
        path[1] = i_weth;

      uint256 ethBefore = address(this).balance;
      uint256 stethBefore = lidoRouter.balanceOf(address(this));

    dexRouter.swapExactTokensForETHSupportingFeeOnTransferTokens(amount, 0, path, address(msg.sender) , block.timestamp);

    uint256 ethAfter = address(this).balance;

    lidoRouter.submit{value: ethAfter - ethBefore }(address(msg.sender));

    uint256 stethAfter = lidoRouter.balanceOf(address(this));

    uint256 mintedAmount = stethAfter - stethBefore;

    stakedAmount[sender] += mintedAmount;`

this doesn't involve any thig with ETH but instead i am simply trying to swap token to weth and then stake it on lido

**Comment by benjamin852** [comment]
Okay thanks this is helpful. Are you able to manually run the `execute` function to see if you can trigger the revert yourself?

I suspect the swap is failing, though because you're sending the ETH output to `msg.sender` and the `msg.sender` is in fact not a `payable` contract. Could you test with a different address other than `msg.sender` receiving the funds just to see if that's the root of the problem?

**Comment by RaumTora** [comment]
@benjamin852 Well i can't see my transaction that i am initiating on axelar ITS Service. On the Axelar Explorer , it just shows now Transaction not found even though the same logic is being applied - 

https://testnet.axelarscan.io/tx/1A74646E82533D99E9DF1CB87290A0ED7CD1131C84F928F4DC1B0F492B8AEEDB

https://testnet.axelarscan.io/tx/C7452BC5E8CD83E1960EC67ADAC50FF92A08D02FD225704284F0841B55DD8E41

Anyhow the transactions were successful on the XRPL Ledger side - https://test.bithomp.com/en/tx/3071F8E3B4AC1EEB3436BA6346B7C381899590BDA2A1F1A3DAC9968D16F53119

Would love to know why it's happening when it worked few days ago

**Comment by benjamin852** [comment]
Right, it seems the receiver (`0xfa2b78fd59e3e86425e7bee5768fa5e7fa41d18c`) is a contract on sepolia correct? You're right that there appears to be an indexing issue on axelarscan that I've flagged to the team to fix, but the tx is likely reverting on this contract you had tried to send to on the sepolia side which is why it's not getting executed there either (regardless of the indexing issue on axelarscan). Can you confirm if you have a custom executable logic in that [contract](https://sepolia.etherscan.io/address/0xfa2b78fd59e3e86425e7bee5768fa5e7fa41d18c) which was deployed a few days ago?

**Comment by RaumTora** [comment]
@benjamin852 Yes the i will provide the sample code for the exection logic that i have in the interchainexecutable function 

`IERC20(usdcToken).approve(address(dexRouter), amount);
    
      address[] memory path = new address[](2);
        path[0] = address(usdcToken);
        path[1] = i_weth;

      uint256 ethBefore = address(this).balance;
      uint256 stethBefore = lidoRouter.balanceOf(address(this));

    dexRouter.swapExactTokensForETHSupportingFeeOnTransferTokens(amount, 0, path, address(this) , block.timestamp);

    uint256 ethAfter = address(this).balance;

    lidoRouter.submit{value: ethAfter - ethBefore }(address(msg.sender));`

Same logic we are implemeting in CCIP and CCTP as well though we can change the logic and try  again after we have the indexing issue fix as we have tried with the new updated logic for the scenario and are waiting for the indexing issue to fix to see if it works

**Comment by benjamin852** [comment]
Okay, in this new snippet you’re now swapping to `address(this)` instead of `msg.sender`, so that should fix the previous safeTransferETH revert you were hitting.

On the indexing side, those two txs you shared still aren’t showing up on AxelarScan due to the issue I mentioned. Have you tried sending any newer cross-chain txs since then? Are they also not indexing, or is it just these two?

**Comment by RaumTora** [comment]
@benjamin852 It is still not working here ist he test transaction i did - 

https://testnet.axelarscan.io/tx/43910C9D78B771E7E8121CF6CB3AA574069767AFB2353B3DC55669F17897454E

Is it not yet resolved?

**Comment by benjamin852** [comment]
Hey @RaumTora Looking into this one still^. But can you please attempt to make another tx? I want to see if this is still an ongoing issue and if so will be easier to debug with a fresher tx. Thanks

**Comment by RaumTora** [comment]
@benjamin852 still not working https://testnet.axelarscan.io/tx/F4D95414813BEB19A8D1800DF02E443238529935B95BE2A3D565434AAE23399B

**Comment by benjamin852** [comment]
Well, transactions in general are coming from xrpl so perhaps an issue with the payload but hard for me to tell exactly. Continuing to check

**Comment by Zypheraum** [comment]
@benjamin852 is issue resolved? or would you like us to share transaction again? If possible, could you pls escalate this. Thanks

**Comment by benjamin852** [comment]
@Zypheraum checked with the team that latest transfer did not go through because the gas amount was equal to the transfer amount, so nothing was left to be transferred.
